Add tests for maximum_weighted_matching()
boostorg/graph pull request #400
Opened 2024-12-05 18:57 UTC by jorisvr

New tests to demonstrate the bugs in issue #399

2025-01-14 09:19 UTC, jeremy-murphy commented
Are the heap data structures in Boost.Heap not sufficient? They are mergeable and mutable.
However, even if they are sufficient, I would be happy to simply get a correct implementation first that fixes the bugs and get a fast implementation later. 
What do you think?

2025-01-15 00:37 UTC, jeremy-murphy commented
Thanks for the explanation. There's no problem with adding Boost.Heap as a dependency, as Boost.Graph already depends on many other parts of Boost. Sounds like the efficient algorithm would require adding a new data structure to Boost.Heap to start with, which shouldn't be too difficult, although I'm aware that the maintainer is not all that active any more. Given that the new implementation is much faster anyway, let's defer the efficient algorithm to later. Ultimately it would be nice to have a top-level algorithm that uses a heuristic to pick the fastest algorithm but users are still free to call specific algorithms. (Best of both worlds.)
Ok, now I have to find time to look over this code. Honestly, it could take a couple of weeks, so please be patient.
Thanks for the work!

2025-01-15 08:02 UTC, jorisvr commented
> Sounds like the efficient algorithm would require adding a new data structure to Boost.Heap to start with

I think the concatenable queue may be so special-purpose that it could just stay in BGL, but generalizing it is definitely also a valid option.

> Given that the new implementation is much faster anyway, let's defer the efficient algorithm to later.

Agreed. It occurs to me that the O(V E log(V)) algorithm also needs an `edge_index` property, which breaks backward compatibility. There may be ways to deal with this, but it seems like it will be a more difficult road than the current PR.

> Ok, now I have to find time to look over this code.

I understand. There is no hurry from my side. Thanks for supporting this effort.

2025-01-22 09:30 UTC, jeremy-murphy commented
What's the "nearest ancestor" problem referred to in the documentation for the fast Gabow algorithm? Is that LCA or something else?

2025-01-22 20:20 UTC, jorisvr commented
> What's the "nearest ancestor" problem referred to in the documentation for the fast Gabow algorithm?

To be honest, I don't know. I kept this comment from the documentation by Yi Ji as I saw no reason to remove it.

I know about the existence of that fast algorithm. I tried to read the paper by Gabow but I can not make heads or tails of it. Mehlhorn and Schaefer made an offhand remark that this algorithm may be unpractical (https://dl.acm.org/doi/10.1145/944618.944622 page 7) but that was a long time ago. I'm not aware of any public available implementation.

2025-01-24 08:49 UTC, jeremy-murphy commented
Doesn't surprise me too much. Bender et. al. made a similar remark about the theoretically optimal algorithm for LCA: it just ain't worth it.

2025-01-25 22:14 UTC, jeremy-murphy commented
Citation LCA remark: https://www.sciencedirect.com/science/article/abs/pii/S0196677405000854

2025-01-25 23:13 UTC, jeremy-murphy requested changes
I haven't even got to the code proper yet but here are a few requests and questions to start with.

2025-01-25 23:13 UTC, jeremy-murphy commented on doc/maximum_weighted_matching.html
> +template &lt;typename Graph, typename MateMap, typename VertexIndexMap, typename EdgeWeightMap, bool Verify = true&gt;
Leave the Verify parameter out, it's not worth complicating the interface for. If a user really wants to verify every result, they can write a short wrapper for themselves.

2025-01-25 23:13 UTC, jeremy-murphy commented on doc/maximum_weighted_matching.html
> +The implementation deviates from the description in [<a href="bibliography.html#galil86">77</a>] on a few points:
I think you need to provide more explanation and evidence about why these deviations from an algorithm published in a refereed journal are good. Even better would be to get your deviations published in a journal. :)

2025-01-25 23:13 UTC, jeremy-murphy commented on doc/maximum_weighted_matching.html
> +For <tt>brute_force_maximum_weighted_matching</tt>, the time complexity is exponential of <i>m</i>.
I could be mistaken, but I think the correct phrasing is "exponential _in_" rather than "exponential _of_".

2025-01-25 23:13 UTC, jeremy-murphy commented on test/Jamfile.v2
> +    [ run weighted_matching_test2.cpp ]
Does it need to be a second file? Just wondering why.

2025-01-26 12:28 UTC, jorisvr commented on doc/maximum_weighted_matching.html
> +template &lt;typename Graph, typename MateMap, typename VertexIndexMap, typename EdgeWeightMap, bool Verify = true&gt;
You are asking to remove `Verify` as parameter, and just never verify the result when called through this function. Right?

Note that verification requires access to the blossom structure and dual variables, which are not returned by this function. So a user who wants to verify, will have to write their own interface function that reaches into `boost::graph::detail::maximum_weighted_matching_context`.

At that point, should we consider to just remove the verification code entirely?
I'm fine with removing it. I personally think that always verifying has merits, but I agree it is a trade-off against complication of the code.

2025-01-26 12:41 UTC, jorisvr commented on doc/maximum_weighted_matching.html
> +The implementation deviates from the description in [<a href="bibliography.html#galil86">77</a>] on a few points:
I see your point, but I'd like to understand how you want me to solve it.

The text already describes the benefit of each deviation. If you just want me to elaborate, I can e.g. expand each bullet into a full paragraph, provide some details, etc.

The reference paper has a focus on time complexity, not practical efficiency. From a complexity point of view, these deviations are trivial tinkering since the time complexity remains the same. If you want, I can provide specific arguments to point this out.

Reusing labels is not my original idea. It is widely used, for example Mehlhorn and Schäfer [1], LEMON, Kolmogorov [2]. But they all use different base algorithms, O(V E log(V)) and O(V^2 E) respectively, therefore the performance trade-off is different. I did some informal benchmarking on random graphs, but printing benchmarks in the documentation seems out-of-place to me.

[1] https://dl.acm.org/doi/abs/10.1145/944618.944622
[2] https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=930b9f9c3bc7acf3277dd2361076d40ff03774b2

2025-01-26 12:48 UTC, jorisvr commented on test/Jamfile.v2
> +    [ run weighted_matching_test2.cpp ]
I was initially apprehensive about changing existing code and thought it best to keep the new stuff separate.

The files can be merged. The styles are quite different though. `weighted_matching_test` reads testcases from a data file, while `test2` builds testcases in commented C++ code. I prefer to keep the coded style for the new test cases.

Let me know if you want me to merge into a single test program.

2025-01-26 12:49 UTC, jorisvr commented on doc/maximum_weighted_matching.html
> +For <tt>brute_force_maximum_weighted_matching</tt>, the time complexity is exponential of <i>m</i>.
Agreed. Fixed.

2025-01-26 12:50 UTC, jorisvr commented on test/weighted_matching_test2.cpp
> +#include <vector>
Fixed. Thanks.

2025-01-29 09:40 UTC, jeremy-murphy commented on doc/maximum_weighted_matching.html
> +template &lt;typename Graph, typename MateMap, typename VertexIndexMap, typename EdgeWeightMap, bool Verify = true&gt;
Yes, I think if we're not confident that the algorithm is reliable then we just have to test it more until we are. Releasing it with an option to check that the result is as expected just kind of screams of a lack of quality.
On principle, we should return these blooms and other things anyway as a tuple of values that the user can just ignore if they're not interested in them. That also makes it simple for us to do this verification when we need to, without having to modify the function. (Which will be the case any time we make a change to the logic.)
Now, having said that, I hope you don't have to make too many changes to the design just so that you can return these internals.

2025-01-29 09:44 UTC, jeremy-murphy commented on doc/maximum_weighted_matching.html
> +template &lt;typename Graph, typename MateMap, typename VertexIndexMap, typename EdgeWeightMap, bool Verify = true&gt;
I'm not 100% sure yet, but the verification code might not belong in the Boost.Graph library itself, but it would definitely belong in something that _fuzzes_ it. That does exist elsewhere, so that could be a next step after getting this PR finished.

2025-01-29 18:34 UTC, jorisvr commented on doc/maximum_weighted_matching.html
> +template &lt;typename Graph, typename MateMap, typename VertexIndexMap, typename EdgeWeightMap, bool Verify = true&gt;
Ok. It seems clear that we are not going to verify answers by default, and I agree with your reasoning for that decision.

I would then recommend to just remove the verification routine. Normal users are not going to use it. The verification logic itself is not trivial. Keeping such unused code in the library will just be a burden.

Putting the verification code in a fuzzer is interesting. I guess the fuzzer can just directly access the internal class to reach the data it needs. Alternatively, the fuzzer can compare answers against a trusted 3rd party implementation like LEMON.

Returning the blossom structure and duals is possible, but these data then need to be rearranged into a suitable structure at the end of the algorithm. During the algorithm, I need them in an efficient form. Returning this seems like more trouble than it is worth. It would also expose internal details about the algorithm, possibly complicating future revisions.

If you agree, I will add a commit to drop the verification stuff.

2025-01-29 22:54 UTC, jeremy-murphy commented on doc/maximum_weighted_matching.html
> +template &lt;typename Graph, typename MateMap, typename VertexIndexMap, typename EdgeWeightMap, bool Verify = true&gt;
Yeah, let's focus on the primary goal: fixing the implementation. We can always add more or tweak it later. So yes, for now let's remove the verification code altogether and don't worry about returning the blossom structures.

2025-01-29 23:00 UTC, jeremy-murphy commented on test/Jamfile.v2
> +    [ run weighted_matching_test2.cpp ]
It's fine, leave them separate, but maybe rename their suffix to distinguish how they're different. It's not too important.

2025-01-31 07:31 UTC, jorisvr commented on doc/maximum_weighted_matching.html
> +template &lt;typename Graph, typename MateMap, typename VertexIndexMap, typename EdgeWeightMap, bool Verify = true&gt;
Done.

2025-01-31 07:35 UTC, jorisvr commented on doc/maximum_weighted_matching.html
> +The implementation deviates from the description in [<a href="bibliography.html#galil86">77</a>] on a few points:
I expanded the text a bit to argue explicitly that each change preserves the overall time complexity and correctness of the algorithm.

2025-02-05 10:59 UTC, jeremy-murphy commented on doc/maximum_weighted_matching.html
> +The implementation deviates from the description in [<a href="bibliography.html#galil86">77</a>] on a few points:
Thanks. I'm still not hugely comfortable with unpublished changes to a published algorithm, but I don't want to be rude and throw out your valuable contribution. 
Since after all it fixes the known bugs, I think the pragmatic thing to do is accept it as is and let the community figure out if it's right. :)

2025-02-05 11:05 UTC, jeremy-murphy requested changes
Sorry, just a trivial request, but since the library is C++14 now can you please use `using` instead of `typedef` and remove spaces from in-between nested template <<....>> brackets? Thanks. I will enable clang-format one day...
PS. I mean, a template should be written as
`template <typename Foo>`, etc.

2025-02-05 11:34 UTC, jeremy-murphy reviewed
Not quite finished...

2025-02-05 11:34 UTC, jeremy-murphy commented on test/weighted_matching_test2.cpp
> +        run_random_graph< double >(10, 15, rng);
Please remove the random graphs, that should be moved to fuzz testing. Unit tests should specifically exercise different paths through the algorithm and edge cases, with as few tests as possible.

2025-02-05 11:34 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +class brute_force_matching
I think we need to be specific about which algorithm this is, since everything is in the same namespace. Also, maybe _matcher_ is better than _matching_?

2025-02-05 11:34 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +    const Graph& g;
Add a general rule, please don't use references as member variables, as they prevent the class from being Regular. Uglier as it might be, just use a pointer.

2025-02-05 11:34 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +    std::vector<bool> got_vertex(nv);
Make sure this is really what you want, as opposed to a bitset.

2025-02-05 11:34 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +    typedef std::deque< vertex_pair_t > alternating_path_t;
deque is rarely faster than vector in practice: did you benchmark?

2025-02-05 11:34 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +        std::list< sub_blossom_t > subblossoms;
And list is typically much much worse than vector; did you benchmark?

2025-02-05 11:34 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +        const nontrivial_blossom_t* ntb = blossom->nontrivial();
Just use auto?

2025-02-05 21:00 UTC, jorisvr commented on test/weighted_matching_test2.cpp
> +        run_random_graph< double >(10, 15, rng);
Ok, done.

2025-02-05 21:03 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +class brute_force_matching
I kept this piece of code unchanged from the previous version. But I'm happy to change it. Shall I make it `class brute_force_maximum_weighted_matcher` ?

2025-02-05 21:12 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +    std::vector<bool> got_vertex(nv);
I believe `std::bitset<N>` requires its size to be fixed at compile time. But I need an array which is sized at run time to match the number of vertices of the graph.

2025-02-05 21:15 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +    typedef std::deque< vertex_pair_t > alternating_path_t;
I add elements on both sides of the deque while tracing the path in two directions. To do that with a vector requires some extra tricks.

2025-02-05 21:19 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +        std::list< sub_blossom_t > subblossoms;
I had not benchmarked, but I have now and there is no measurable difference. This list is not accessed very often.

I chose list because I use `splice()` to reorient the base of the list during augmentation. It is just a matter of convenience. I can instead use vector and either extra bookkeeping or copying of elements.

Do you prefer `std::vector` over `std::list` in cases where the performance is neutral?

2025-02-05 21:21 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +        const nontrivial_blossom_t* ntb = blossom->nontrivial();
I don't understand.
Do you mean `auto func` instead of `template <typename Func>` ? That was not allowed before C++20.

Or do you mean `auto ntb` instead of `const nontrivial_blossom_t* ntb` ?

2025-02-05 23:05 UTC, jeremy-murphy reviewed
Still going,..

2025-02-06 01:52 UTC, jeremy-murphy commented
There are some functions that take a `blossom*` but require that it is not null, in which case they should take a reference instead.

2025-02-06 02:02 UTC, jeremy-murphy commented
That's all from me, once the last comments are resolved I'll merge it in.
Overall I love the code, so thank you!

2025-02-06 02:05 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +    const Graph& g;
Yeah it's used in existing code, but it's a bad practice, so let's not add more.

2025-02-06 23:17 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +    const Graph& g;
Ok, done.

2025-02-06 23:25 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +        const nontrivial_blossom_t* ntb = blossom->nontrivial();
Ok. I changed it to `auto` for these and a few similar verbose declarations.

Is that what you had in mind, or do you want to push further towards the *almost-alway-auto* style?

2025-02-06 23:25 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +        const bool is_nontrivial_blossom;
Done.

2025-02-06 23:31 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +            if ((! edge.has_value()) || (s < slack))
Oh, I probably came up with this. I don't see it anywhere else in BGL.
I removed the spaces now.

I really like the space, but this is not the time to start a discussion about code formatting.

2025-02-06 23:39 UTC, jorisvr commented
> There are some functions that take a `blossom*` but require that it is not null, in which case they should take a reference instead.

I now changed these into `blossom&`.
This involved adding a number of `*` and `&` operators in the code. Because `blossom*` is still the native type in several data structures, I end up going back-and-forth between pointer and reference. In my opinion, it makes the code less clear. But I can live with it.

2025-02-10 02:16 UTC, jeremy-murphy commented
> > There are some functions that take a `blossom*` but require that it is not null, in which case they should take a reference instead.
> 
> I now changed these into `blossom&`. This involved adding a number of `*` and `&` operators in the code. Because `blossom*` is still the native type in several data structures, I end up going back-and-forth between pointer and reference. In my opinion, it makes the code less clear. But I can live with it.

I know what you mean, sometimes you just have to pay a price for doing things correctly, but it also might mean that those other places using `blossom*` could do with some refactoring.

2025-02-10 02:24 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +        const nontrivial_blossom_t* ntb = blossom->nontrivial();
I personally use and recommend AAA style, but what you've done here is fine. I just felt those long typenames with qualifiers were not helping the readability.

2025-02-10 02:25 UTC, jeremy-murphy approved these changes

2025-02-10 02:26 UTC, merged

2025-02-24 22:15 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +    const Graph& g;
Something recently reminded me that there is a better way to do this than using a raw pointer, which is to use `std::reference_wrapper`. 
https://en.cppreference.com/w/cpp/utility/functional/reference_wrapper
It might not be a perfect solution but I would definitely have a go at using it to see if it improves readability.

2025-02-25 22:09 UTC, jorisvr commented on include/boost/graph/maximum_weighted_matching.hpp
> +    const Graph& g;
> `std::reference_wrapper`

I did look into that, but I could not get it to work in a way that seems helpful.
In particular, the following does not work:

```
std::reference_wrapper<const Graph> g;

...
auto nv = num_vertices(g);
```

If I write that, I get a type error. Although `std::reference_wrapper` is supposedly implicitly convertable to the stored reference type, that doesn't seem to work in this case. Perhaps because `num_vertices()` is a function template, the reference wrapper itself ends up being passed as function argument.

I _can_ write `num_vertices(g.get())`
but I'm not sure it is much of an improvement over `num_vertices(*g)`.

2025-02-26 09:20 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +    std::vector<bool> got_vertex(nv);
I forgot to address this one, whoops. 
`vector<bool>` is generally avoided because of its unusual performance trying to satisfy the standard container interface (providing a reference to each element via iteration) whilst only using one bit per value, which requires the use of a proxy class, etc. 
A dynamic bitset is just more honest about what it is and does.
It's not a big deal, might not need to be changed until someone makes some other changes in there.

2025-02-26 09:21 UTC, jeremy-murphy commented on include/boost/graph/maximum_weighted_matching.hpp
> +    const Graph& g;
Ahhh, yeah, it doesn't magically remove in that case. Oh well, too bad.