Make adjacency_matrix implement BidirectionalGraph concept
boostorg/graph pull request #403
Opened 2024-12-12 03:07 UTC by Wavetrace

Adjacency matrix is by nature bidirectional and one can see that the concept was mostly implemented before. That implementation missed the degree function(s). These functions are implemented in this commit and the traversal_category is updated to meet the concept requirements.

Tests are also added, though they are a bit shallow in the sense that they seem to omit intensive algorithms.

This PR is a consequence of work on https://github.com/boostorg/graph/pull/397 -- that one contains a test commented out, that ends up running `neighbor_bfs` on an adjacency matrix.

2025-02-25 09:40 UTC, jeremy-murphy requested changes

2025-02-25 09:40 UTC, jeremy-murphy commented on include/boost/graph/adjacency_matrix.hpp
> +// degree
This comment is not doing much work. :)

2025-02-28 05:59 UTC, jeremy-murphy commented
I thought it would be expedient to just fix the comments myself since the changes were trivial.

2025-02-28 06:03 UTC, jeremy-murphy approved these changes
Thanks for a pragmatic missing piece of the puzzle!

2025-02-28 07:07 UTC, merged

2025-03-04 17:03 UTC, jonasliljenfeldt commented
Nice one @Wavetrace!

2025-03-04 18:51 UTC, Wavetrace commented
Thanks, Jonas! Thanks a lot, Jeremy for fixing the comment!