examples: C++11: Use auto.
boostorg/graph pull request #411
Opened 2024-12-25 13:26 UTC by murraycu

This is a small step - part of a larger old pull request to modernize the examples: https://github.com/boostorg/graph/pull/81

2024-12-30 07:36 UTC, jeremy-murphy commented
Can you check why it's (still) failing?

2025-01-01 22:23 UTC, jeremy-murphy commented on include/boost/graph/bc_clustering.hpp
> +        auto e = *max_element(edges_iters.first, edges_iters.second, cmp);
I haven't checked the whole diff, but this one change that doesn't fit with the stated purpose of the pull request is broken.  :)

2025-01-06 12:04 UTC, murraycu commented on include/boost/graph/bc_clustering.hpp
> +        auto e = *max_element(edges_iters.first, edges_iters.second, cmp);
Thanks. Resolving the conflicts was awkward. I'll mark this as Ready for Review again when I've checked more carefully.

2025-01-23 10:01 UTC, jeremy-murphy requested changes
Thanks for an important modernization that shows users that Boost.Graph can be used with C++11!
Just a few small changes I would like before merging it.

2025-02-02 14:41 UTC, murraycu commented on example/boost_web_graph.cpp
> +    using NameMap = property_map< Graph, vertex_name_t >::type;
No idea. Removed. Thanks.

2025-02-02 14:45 UTC, murraycu commented on example/edge-function.cpp
> +    typedef property_map< graph_type, vertex_name_t >::type name_map_t;
Sure, done, though this was actually just moving the line down from above.

2025-02-02 14:48 UTC, murraycu commented on example/filtered_graph_edge_range.cpp
> +              Graph;
Done.

This was presumably a result of me running clang-format via "git format-patch HEAD^".

2025-02-02 14:53 UTC, murraycu commented on example/cycle_ratio_example.cpp
> +    for (const auto& edge : cc)
Done, here and in other changes in this PR, though existing code use west const.

I do prefer east const, so maybe we should change it throughout to be consistent, separately?

2025-02-02 15:04 UTC, murraycu commented on example/boost_web_graph.cpp
> +    using NameMap = property_map< Graph, vertex_name_t >::type;
Actually, this was just moved down from higher up in this file. It is needed. I've changed it to a "using" as you requested in another comment.

2025-02-03 06:02 UTC, jeremy-murphy commented on example/cycle_ratio_example.cpp
> +    for (const auto& edge : cc)
Good question. Although I believe firmly in East const, I try not to be militant about it and I think most of the time it just doesn't matter, so I'll be happy to introduce it in new code and when things change but not sure if I'll enact a sweeping change of the repo for it.

2025-02-03 06:05 UTC, jeremy-murphy approved these changes

2025-02-03 06:05 UTC, merged